apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hpcopt-api
  namespace: hpcopt
  labels:
    app.kubernetes.io/name: hpcopt-api
    app.kubernetes.io/part-of: hpc-workload-optimizer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hpcopt-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
