from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class CoverageStat:
    package: str
    hit_lines: int
    total_lines: int

    @property
    def percent(self) -> float:
        if self.total_lines == 0:
            return 0.0
        return (self.hit_lines * 100.0) / self.total_lines


def _parse_package_threshold(raw: str) -> tuple[str, float]:
    if "=" not in raw:
        raise ValueError(f"Invalid package threshold '{raw}'; expected <package>=<percent>.")
    package, threshold = raw.split("=", 1)
    package = package.strip()
    if not package:
        raise ValueError(f"Invalid package threshold '{raw}'; package name is empty.")
    try:
        threshold_value = float(threshold.strip())
    except ValueError as exc:
        raise ValueError(f"Invalid package threshold '{raw}'; percent must be numeric.") from exc
    return package, threshold_value


def _class_lines(class_node: ET.Element) -> tuple[int, int]:
    hit = 0
    total = 0
    lines_parent = class_node.find("lines")
    if lines_parent is None:
        return hit, total
    for line_node in lines_parent.findall("line"):
        hits_raw = line_node.attrib.get("hits", "0")
        try:
            hits = int(hits_raw)
        except ValueError:
            hits = 0
        total += 1
        if hits > 0:
            hit += 1
    return hit, total


def _collect_package_coverage(root: ET.Element, package: str) -> CoverageStat:
    prefix = f"python/hpcopt/{package}/"
    hit = 0
    total = 0
    for class_node in root.findall(".//class"):
        filename = class_node.attrib.get("filename", "")
        if not filename.startswith(prefix):
            continue
        cls_hit, cls_total = _class_lines(class_node)
        hit += cls_hit
        total += cls_total
    return CoverageStat(package=package, hit_lines=hit, total_lines=total)


def _collect_global_coverage(root: ET.Element) -> CoverageStat:
    hit = 0
    total = 0
    for class_node in root.findall(".//class"):
        cls_hit, cls_total = _class_lines(class_node)
        hit += cls_hit
        total += cls_total
    return CoverageStat(package="global", hit_lines=hit, total_lines=total)


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate global and package-level coverage thresholds.")
    parser.add_argument(
        "--coverage-xml",
        type=Path,
        default=Path("coverage.xml"),
        help="Path to coverage XML generated by pytest-cov.",
    )
    parser.add_argument(
        "--global-fail-under",
        type=float,
        default=86.0,
        help="Global minimum line coverage percentage.",
    )
    parser.add_argument(
        "--package-threshold",
        action="append",
        default=[],
        help="Package minimum coverage in form '<package>=<percent>' (repeatable).",
    )
    args = parser.parse_args()

    if not args.coverage_xml.exists():
        print(f"ERROR: coverage XML not found: {args.coverage_xml}")
        return 1

    try:
        root = ET.fromstring(args.coverage_xml.read_text(encoding="utf-8"))
    except (ET.ParseError, OSError) as exc:
        print(f"ERROR: failed to parse coverage XML: {exc}")
        return 1

    errors: list[str] = []
    global_stat = _collect_global_coverage(root)
    print(
        f"Coverage global: {global_stat.percent:.2f}% "
        f"({global_stat.hit_lines}/{global_stat.total_lines}) "
        f"(threshold {args.global_fail_under:.2f}%)"
    )
    if global_stat.percent < args.global_fail_under:
        errors.append(
            f"Global coverage {global_stat.percent:.2f}% below required {args.global_fail_under:.2f}%."
        )

    parsed_thresholds: list[tuple[str, float]] = []
    for raw in args.package_threshold:
        try:
            parsed_thresholds.append(_parse_package_threshold(raw))
        except ValueError as exc:
            errors.append(str(exc))

    for package, threshold in parsed_thresholds:
        stat = _collect_package_coverage(root, package)
        print(
            f"Coverage {package}: {stat.percent:.2f}% "
            f"({stat.hit_lines}/{stat.total_lines}) "
            f"(threshold {threshold:.2f}%)"
        )
        if stat.total_lines == 0:
            errors.append(f"Package '{package}' has no measured lines in coverage XML.")
            continue
        if stat.percent < threshold:
            errors.append(f"Package '{package}' coverage {stat.percent:.2f}% below required {threshold:.2f}%.")

    if errors:
        print("Coverage thresholds: FAIL")
        for err in errors:
            print(f"- {err}")
        return 1

    print("Coverage thresholds: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
